### ISSUE TITLE
Error on NodeJS v8.1.4 

### ISSUE THREAD

**Issue by paulomcnally** [excellenteasy/android-splash-generate#3]
```
/home/polin/.node-gyp/8.1.4/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
lwip_decoder.target.mk:168: recipe for target 'Release/obj.target/lwip_decoder/src/decoder/init.o' failed
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory '/home/polin/.nvm/versions/node/v8.1.4/lib/node_modules/android-splash-generate/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/polin/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.4.0-83-generic
gyp ERR! command "/home/polin/.nvm/versions/node/v8.1.4/bin/node" "/home/polin/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/polin/.nvm/versions/node/v8.1.4/lib/node_modules/android-splash-generate/node_modules/lwip
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/polin/.npm/_logs/2017-07-21T02_02_31_091Z-debug.log
➜  ~ 

```

**Comment by davidpfahler** [comment]
@paulomcnally Thank you for reporting this problem. There is an installation problem in the underlying `lwip` dependency. The issue is being tracking [in the `lwip` repo here](https://github.com/EyalAr/lwip/issues/306). Once that issue is resolved, we can update this package and hopefully solve the problem you reported.
